import os
import pytest
from unittest.mock import AsyncMock, patch, MagicMock

from app.services.video.remote_wan import RemoteWanVideoProvider
from app.services.video.factory import get_video_provider
from app.models.generation import Generation
from app.schemas.common import GenerationStatus
from app.core.config import settings
from app.core.exceptions import (
    RemoteWANConfigurationErrorException,
    RemoteWANUnavailableException,
    RemoteWANTimeoutException,
    RemoteWANAuthenticationErrorException,
    RemoteWANGenerationFailedException,
    RemoteWANInvalidResultException,
)


def test_remote_wan_factory_selection():
    settings.VIDEO_PROVIDER = "remote_wan"
    provider = get_video_provider()
    assert provider.__class__.__name__ == "RemoteWanVideoProvider"
    settings.VIDEO_PROVIDER = "mock"


@pytest.mark.asyncio
async def test_remote_wan_missing_config():
    provider = RemoteWanVideoProvider(remote_url="")
    gen = Generation(id="gen-remote-no-config", original_prompt="test prompt")
    with pytest.raises(RemoteWANConfigurationErrorException):
        await provider.submit_generation(gen)


@pytest.mark.asyncio
async def test_remote_wan_successful_generation(tmp_path):
    provider = RemoteWanVideoProvider(
        remote_url="http://mock-gpu-worker:8002",
        api_key="secret-bearer-key",
        timeout_seconds=30
    )
    gen = Generation(
        id="moviq-gen-remote-test-1",
        original_prompt="A massive ancient temple emerging from a dense jungle at sunrise",
        enhanced_prompt="Cinematic 35mm shot of a massive ancient temple emerging from a dense jungle at sunrise...",
        negative_prompt="blurry",
        aspect_ratio="16:9",
        duration="5s"
    )

    mock_post_resp = MagicMock()
    mock_post_resp.status_code = 200
    mock_post_resp.json.return_value = {
        "status": "completed",
        "generation_id": "moviq-gen-remote-test-1",
        "video_url": "/videos/moviq_moviq-gen-remote-test-1.mp4"
    }

    mock_dl_resp = MagicMock()
    mock_dl_resp.status_code = 200
    mock_dl_resp.content = b"fake binary MP4 video payload generated by remote Wan2.1 GPU worker"

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_post_resp)
    mock_client.get = AsyncMock(return_value=mock_dl_resp)

    mock_cm = AsyncMock()
    mock_cm.__aenter__.return_value = mock_client

    with patch("httpx.AsyncClient", return_value=mock_cm):
        job_id = await provider.submit_generation(gen)
        assert job_id.startswith("remote-wan-job-")

        import asyncio
        await asyncio.sleep(0.4)

        # Verify POST payload sent to remote worker contains ENHANCED prompt & Bearer token
        mock_client.post.assert_called_once()
        call_kwargs = mock_client.post.call_args
        url_arg = call_kwargs[0][0]
        json_kw = call_kwargs[1]["json"]
        headers_kw = call_kwargs[1]["headers"]

        assert url_arg == "http://mock-gpu-worker:8002/generate"
        assert json_kw["prompt"] == gen.enhanced_prompt
        assert headers_kw["Authorization"] == "Bearer secret-bearer-key"

        status, pct = await provider.check_status(job_id)
        assert status == GenerationStatus.COMPLETED

        result = await provider.get_result(job_id)
        assert result["video_url"] == "/api/v1/generations/moviq-gen-remote-test-1/video"

        # Verify local file saved
        filepath = os.path.join(os.getcwd(), "generated", "moviq_moviq-gen-remote-test-1.mp4")
        assert os.path.exists(filepath)


@pytest.mark.asyncio
async def test_remote_wan_original_prompt_fallback():
    provider = RemoteWanVideoProvider(remote_url="http://mock-gpu-worker:8002")
    gen = Generation(
        id="gen-orig-prompt-fallback",
        original_prompt="A cybernetic eagle",
        enhanced_prompt=None
    )

    mock_post_resp = MagicMock()
    mock_post_resp.status_code = 200
    mock_post_resp.json.return_value = {"video_url": "/videos/test.mp4"}

    mock_dl_resp = MagicMock()
    mock_dl_resp.status_code = 200
    mock_dl_resp.content = b"content"

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_post_resp)
    mock_client.get = AsyncMock(return_value=mock_dl_resp)

    mock_cm = AsyncMock()
    mock_cm.__aenter__.return_value = mock_client

    with patch("httpx.AsyncClient", return_value=mock_cm):
        job_id = await provider.submit_generation(gen)
        import asyncio
        await asyncio.sleep(0.3)

        call_kwargs = mock_client.post.call_args
        json_kw = call_kwargs[1]["json"]
        assert json_kw["prompt"] == "A cybernetic eagle"


@pytest.mark.asyncio
async def test_remote_wan_auth_error():
    provider = RemoteWanVideoProvider(remote_url="http://mock-gpu-worker:8002")
    gen = Generation(id="gen-auth-error", original_prompt="test")

    mock_post_resp = MagicMock()
    mock_post_resp.status_code = 401

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_post_resp)

    mock_cm = AsyncMock()
    mock_cm.__aenter__.return_value = mock_client

    with patch("httpx.AsyncClient", return_value=mock_cm):
        job_id = await provider.submit_generation(gen)
        import asyncio
        await asyncio.sleep(0.3)

        with pytest.raises(RemoteWANAuthenticationErrorException):
            await provider.check_status(job_id)


@pytest.mark.asyncio
async def test_remote_wan_empty_video_rejection():
    provider = RemoteWanVideoProvider(remote_url="http://mock-gpu-worker:8002")
    gen = Generation(id="gen-empty-video", original_prompt="test")

    mock_post_resp = MagicMock()
    mock_post_resp.status_code = 200
    mock_post_resp.json.return_value = {"video_url": "/videos/empty.mp4"}

    mock_dl_resp = MagicMock()
    mock_dl_resp.status_code = 200
    mock_dl_resp.content = b""  # Empty 0-byte MP4

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_post_resp)
    mock_client.get = AsyncMock(return_value=mock_dl_resp)

    mock_cm = AsyncMock()
    mock_cm.__aenter__.return_value = mock_client

    with patch("httpx.AsyncClient", return_value=mock_cm):
        job_id = await provider.submit_generation(gen)
        import asyncio
        await asyncio.sleep(0.3)

        with pytest.raises(RemoteWANInvalidResultException):
            await provider.check_status(job_id)


@pytest.mark.asyncio
async def test_remote_wan_http_500_error_preservation():
    provider = RemoteWanVideoProvider(remote_url="http://mock-gpu-worker:8002")
    gen = Generation(id="gen-http-500", original_prompt="test")

    mock_post_resp = MagicMock()
    mock_post_resp.status_code = 500
    mock_post_resp.text = '{"detail": "Wan generation failed: NameError: name \'pipe\' is not defined"}'

    mock_client = AsyncMock()
    mock_client.post = AsyncMock(return_value=mock_post_resp)

    mock_cm = AsyncMock()
    mock_cm.__aenter__.return_value = mock_client

    with patch("httpx.AsyncClient", return_value=mock_cm):
        job_id = await provider.submit_generation(gen)
        import asyncio
        await asyncio.sleep(0.3)

        with pytest.raises(RemoteWANGenerationFailedException) as exc_info:
            await provider.check_status(job_id)
        
        assert "NameError" in str(exc_info.value) or "500" in str(exc_info.value)

